### ISSUE TITLE
npm install error.

### ISSUE THREAD

**Issue by Agarian** [AJS-development/OgarUL-Client#1]
npm ERR! install Couldn't read dependencies
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.3/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! file /home/ubuntu/workspace/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 12:3
npm ERR!   }
npm ERR!   ^
npm ERR! File: /home/ubuntu/workspace/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by Agarian** [comment]
i will make pr to fix

**Comment by Agarian** [comment]
but i get "Cannot GET /" instead of the page loading.

**Comment by LegitSoulja** [comment]
@Agarian its not a client. Therefor, nothing is in "/" directory.

**Comment by LegitSoulja** [comment]
@Agarian and if you have a client, you have to have atleast a default index.html page, or if not change ./client/ to /client/whatever_file_first.html,

**Comment by LegitSoulja** [comment]
@Agarian and I fixed package.json. You probably already have.

**Comment by Agarian** [comment]
i made a PR on it already :p
