### ISSUE TITLE
Pupup in play.ogarul.tk site

### ISSUE THREAD

**Issue by jollesnaas** [AJS-development/OgarUL-Client#4]
Does any one know the full code for the pupup on play.ogarul.tk (That were you choose a server, I want to edit the pupup itself)
Ps. I know how to create a simple one with text I want that one with the console connect command!

Thanks!

**Comment by Andrews54757** [comment]
wsconnect on main_out.js

**Comment by jollesnaas** [comment]
So what is the html code?
